### ISSUE TITLE
Plan going forward

### ISSUE THREAD

**Issue by jakoss** [Pozo/mapstruct-kotlin#2]
Hi,

This project seems to be first Kotlin-friendly attempt to model mapping. Since there is a new (final) release of MapStruct 1.3.0 do you have any plans to publish this library to the public?

**Comment by Pozo** [comment]
Hi @Nekromancer !

Thanks for your question. Yes, I have. 

I plan to publish this to maven central and/or jcenter. You might expect this around mid/end of October since right now I'm very busy and I couldn't find a spot for this project.

In the meantime feel free to ask any question, and remind me this after a few weeks.

Cheers.

**Comment by jakoss** [comment]
Hi, just a friendly reminder about this! :)

**Comment by Pozo** [comment]
@Nekromancer Thank you for your patience.
The first release is out. I've updated the readme as well.
