### ISSUE TITLE
Align version with mapstruct 1.4.0.Final

### ISSUE THREAD

**Issue by jakoss** [Pozo/mapstruct-kotlin#26]
Hi,

Do you think the library is good for a stable release alongside MapStruct 1.4.0? I've using it for 4 months without an issue :)

**Comment by Pozo** [comment]
Hi @jakoss, I couldn't have a chance to look over the 1.4.0 release entirely, however the good news is that this library might not needed anymore! I just quickly looked over the [release note of the 1.4.0](https://mapstruct.org/news/2020-09-28-mapstruct-1_4_0_Final-is-out/) and they mention that kolin data class mapping is included by default.

 > Here it is included mapping into Kotlin Data Classes and Java 14 records.

If I were in your shoes I would start digging how does it work with pure mapstruct instead of using this library plus mapstruct.

**Comment by jakoss** [comment]
Wow, i missed that since it wasn't on the bullet list. It is working actually. Thanks for the last months anyway!
