### ISSUE TITLE
Invalid builder name for properties named "isXXX"

### ISSUE THREAD

**Issue by lkjh654** [Pozo/mapstruct-kotlin#3]
Hi,

thanks for your great work.
I've observed that for classes with isXXX properties the generated mapper doesn't include mapping of such properties.

For the following class
```
@KotlinBuilder
data class Animal(
    val isDog: Boolean
)
```

`isDog` property will not be mapped in the mapper.
I believe it might be caused by the difference in getter naming

For such a class `isDog()` method will be generated on the bytecode level (and `setDog(boolean var)` for var properties)  However from what I see a `setIsDog()` method will be generated by the KotlinBuilder. There is a mismatch that can cause the MappingProcessor not to find the proper setter and just omitting the property.

**Comment by Pozo** [comment]
@lkjh654 Thank you for the report! I'll look at it soon.

**Comment by Pozo** [comment]
@lkjh654 I just investigated this a bit and this behavior caused by mapstruct. However I think It's not an issue, since if you have a property `isDog` according the bean specification the getter will be `getIsDog` and the builder has this correctly.

See https://github.com/mapstruct/mapstruct/issues/1990 and https://github.com/mapstruct/mapstruct/issues/1943

If you would like to stick to the current variable name I suggest you to use custom `source` and `target` mapping. For instance if you have 

```kotlin
@KotlinBuilder
data class Order(val isShipped: Boolean, val sent: Boolean)

@KotlinBuilder
data class OrderDto(val isShipped: Boolean, val sent: Boolean)
```
You can use something like this
```kotlin
@Mapper
interface OrderMapper {

    @Mappings(
        value = [
            Mapping(source = "shipped", target = "isShipped")
        ]
    )
    fun toDto(order: Order): OrderDto


    @Mappings(
        value = [
            Mapping(source = "shipped", target = "isShipped")
        ]
    )
    fun toOrder(order: OrderDto): Order
}
```
